services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5555:5432"
    networks:
      ai-net:
        aliases:
          - postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  aiarticles-be:
    image: ferdinandurban/aiarticles-be:18122024
    depends_on:
      - postgres
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_ART_OPENAI_PROJECT_API_KEY=${AI_ART_OPENAI_PROJECT_API_KEY}
      - AI_ART_OPENAI_ORGANIZATION_ID=${AI_ART_OPENAI_ORGANIZATION_ID}
      - AI_ART_OPENAI_PROJECT_ID=${AI_ART_OPENAI_PROJECT_ID}
      - AI_ART_OPENAI_ASSISTANT_ID=${AI_ART_OPENAI_ASSISTANT_ID}

      - AI_ART_DB_USER=${AI_ART_DB_USER:-postgres}
      - AI_ART_DB_PASSWORD=${AI_ART_DB_PASSWORD:-postgres}
      - AI_ART_DB_HOST=postgres
      - AI_ART_DB_PORT=5432
      - AI_ART_DB_NAME=ai_articles

      - AI_ART_S3_ACCESS_KEY_ID=${AI_ART_S3_ACCESS_KEY_ID}
      - AI_ART_S3_SECRET_ACCESS_KEY=${AI_ART_S3_SECRET_ACCESS_KEY}
      - AI_ART_S3_ENDPOINT=${AI_ART_S3_ENDPOINT:-https://fra1.digitaloceanspaces.com}
      - AI_ART_S3_REGION=${AI_ART_S3_REGION:-fra1}
      - AI_ART_S3_BUCKET=${AI_ART_S3_BUCKET}
      - AI_ART_S3_IMAGE_FOLDER=${AI_ART_S3_IMAGE_FOLDER:-ai_articles}
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: 10m
        max-file: 10
    networks:
      ai-net:
        aliases:
          - ai-be

networks:
  ai-net:
    driver: bridge
